kind: Service
apiVersion: v1
metadata:
  name: <svc이름> my-first-spark-worker-1-svc
  namespace: default
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: my-first-spark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spark
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: <port번호> 30079
  selector:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: my-first-spark
    app.kubernetes.io/name: spark
    statefulset.kubernetes.io/pod-name: <pod이름> my-first-spark-worker-1
  type: NodePort
